import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#1a1c1f",
        "inverse-primary": "#006875",
        "on-primary-fixed": "#001f24",
        "on-error": "#690005",
        tertiary: "#efecee",
        "on-surface-variant": "#bac9cc",
        "on-primary": "#00363d",
        "inverse-surface": "#e2e2e7",
        primary: "#c3f5ff",
        "surface-container-lowest": "#0c0e12",
        "on-tertiary": "#303032",
        "on-tertiary-fixed": "#1b1b1d",
        "surface-dim": "#111317",
        "surface-container-highest": "#333539",
        "on-tertiary-container": "#59595b",
        "surface-variant": "#333539",
        secondary: "#c8c6c5",
        "on-secondary-fixed-variant": "#474746",
        surface: "#111317",
        "surface-container": "#1e2023",
        "on-primary-fixed-variant": "#004f58",
        "tertiary-container": "#d2d0d2",
        "on-background": "#e2e2e7",
        "on-secondary": "#313030",
        "secondary-fixed-dim": "#c8c6c5",
        "outline-variant": "#3b494c",
        "surface-tint": "#00daf3",
        "primary-fixed": "#9cf0ff",
        outline: "#849396",
        "secondary-container": "#474746",
        "surface-container-high": "#282a2e",
        "inverse-on-surface": "#2e3034",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#00626e",
        "error-container": "#93000a",
        error: "#ffb4ab",
        "primary-fixed-dim": "#00daf3",
        "tertiary-fixed-dim": "#c8c6c8",
        background: "#111317",
        "secondary-fixed": "#e5e2e1",
        "tertiary-fixed": "#e4e2e4",
        "on-secondary-fixed": "#1c1b1b",
        "on-secondary-container": "#b7b5b4",
        "on-surface": "#e2e2e7",
        "on-tertiary-fixed-variant": "#474649",
        "primary-container": "#00e5ff",
        "surface-bright": "#37393d",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1440px",
        unit: "8px",
        "margin-desktop": "80px",
        "margin-mobile": "20px",
        gutter: "24px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "40px", fontWeight: "600" },
        ],
        "label-caps": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.1em",
            fontWeight: "500",
          },
        ],
        "headline-lg": ["48px", { lineHeight: "56px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": [
          "72px",
          {
            lineHeight: "80px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
      },
      maxWidth: {
        "container-max": "1440px",
      },
    },
  },
  plugins: [],
};

export default config;
